[project]
name = "pyplication"
description = "Some app"
dependencies = [
    "flask",
    "beautifulsoup4",
    "requests",
    "nltk",
    "scikit-learn"
]
version = "1.0"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"